    development:
      encoding: utf8
      adapter: postgresql 
      host: sql-mapnik
      database: u_h4ck3rm1k3
    
    test:
      database: db/test.sqlite3
      encoding: utf8
      username: transiki
      password: transiki
      adapter:  sqlite3
      host:     localhost

